/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  openApiSidebar: [
    {
      type: 'category',
      label: 'Koinos API',
      link: {
        type: 'generated-index',
        title: 'Koinos API',
        description:
          'Interact with the Koinos mainnet blockchain via the swagger endpoints located here.',
        slug: '/category/koinos-api'
      },
      // @ts-ignore
      items: require('./docs/koinos/sidebar.js')
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
}

module.exports = sidebars
